### ISSUE TITLE
Expand datetime filtering

### ISSUE THREAD

**Issue by danverkamp** [ge-flight-analytics/emspy#14]
Why can we only use ">=", "<" in datetime filtering?  This should definitely be expanded.

**Comment by richardpineo** [comment]
This is currently a limitation of the EMS API. You can see it in the 'supporting documentation' section of the website under 'filter operator'. I think it wouldn't be too hard to add but that feature request would need to be made to the API (not emspy) section. That said, there may be ways to manipulate the date to use the avialable operators (e.g. convert X > date into (X >= (date + 1 second)).

![image](https://user-images.githubusercontent.com/8593979/55826295-8ef0ad80-5abc-11e9-8ad5-cd66fbfbf412.png)

**Comment by danverkamp** [comment]
Closing, since this is a limitation of the API itself.
