### ISSUE TITLE
FutureWarning nagging message in flight.py line 447

### ISSUE THREAD

**Issue by gh-mikework** [ge-flight-analytics/emspy#18]
There is a nag message displaying for line 447 of flight.py.  I successfully recompiled flight.py by changing 'argmin' to 'idxmin', however I am unsure if this would break something else down the line.

```
c:\python27\lib\site-packages\emspy\query\flight.py:447: FutureWarning: 
The current behaviour of 'Series.argmin' is deprecated, use 'idxmin'
instead.
The behavior of 'argmin' will be corrected to return the positional
minimum in the future. For now, use 'series.values.argmin' or
'np.argmin(np.array(values))' to get the position of the minimum
row.
  return fields.loc[fields.name.str.len().argmin()].to_dict()
```

My current environment:
Python 2.7.16
numpy 1.16.2
pandas 0.24.2
jupyter 4.4.0

**Comment by danverkamp** [comment]
Thanks for submitting this issue, Mike.  I've noticed this as well.  It would be nice to replace the deprecated calls and test to ensure forward compatibility.  I will take a look.

**Comment by delunalara** [comment]
I think this was already fixed in another version, there are currently no calls to `argmin` in `flight.py`
