### ISSUE TITLE
KeyError when running query.select()

### ISSUE THREAD

**Issue by yiyanggu** [ge-flight-analytics/emspy#40]
Hello,

I'm getting the following error when running         
`query.select('Flight Record')`

> Traceback (most recent call last):
> 
>   File "<ipython-input-25-150af9d78166>", line 1, in <module>
>     query.select('Flight Record')
> 
>   File "C:\Users\212566414\AppData\Local\Continuum\anaconda3\lib\site-packages\emspy\query\fltquery.py", line 71, in select
>     fields = self.__flight.search_fields(*args, **kwargs)
> 
>   File "C:\Users\212566414\AppData\Local\Continuum\anaconda3\lib\site-packages\emspy\query\flight.py", line 380, in search_fields
>     fres = get_shortest(fres)
> 
>   File "C:\Users\212566414\AppData\Local\Continuum\anaconda3\lib\site-packages\emspy\query\flight.py", line 447, in get_shortest
>     return fields.loc[fields.name.str.len().argmin()].to_dict()
> 
>   File "C:\Users\212566414\AppData\Roaming\Python\Python37\site-packages\pandas\core\indexing.py", line 1767, in __getitem__
>     return self._getitem_axis(maybe_callable, axis=axis)
> 
>   File "C:\Users\212566414\AppData\Roaming\Python\Python37\site-packages\pandas\core\indexing.py", line 1964, in _getitem_axis
>     return self._get_label(key, axis=axis)
> 
>   File "C:\Users\212566414\AppData\Roaming\Python\Python37\site-packages\pandas\core\indexing.py", line 624, in _get_label
>     return self.obj._xs(label, axis=axis)
> 
>   File "C:\Users\212566414\AppData\Roaming\Python\Python37\site-packages\pandas\core\generic.py", line 3537, in xs
>     loc = self.index.get_loc(key)
> 
>   File "C:\Users\212566414\AppData\Roaming\Python\Python37\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
>     return self._engine.get_loc(self._maybe_cast_indexer(key))
> 
>   File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
> 
>   File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
> 
>   File "pandas\_libs\hashtable_class_helper.pxi", line 997, in pandas._libs.hashtable.Int64HashTable.get_item
> 
>   File "pandas\_libs\hashtable_class_helper.pxi", line 1004, in pandas._libs.hashtable.Int64HashTable.get_item
> 
> KeyError: 0
> 

In my metadata db file, 'Flight Record' keyword can match with two fields. After checking flight.py, in line 380, it's using the get_shortest() function to compare the two fields for length. 

So when looking at get_shortest() function in line 444 in flight.py, the problem seems to associate with the indexing of fields dataframe. So I suggest adding `fields=fields.reset_index(drop=True)` after line 446 in flight.py.

**Comment by patstout** [comment]
#41 should fix this

**Comment by danverkamp** [comment]
> #41 should fix this

I'm going to close this, per Pat.  This was fixed.
