### ISSUE TITLE
Can't filter on measurements with a single quote in the name

### ISSUE THREAD

**Issue by roice3** [ge-flight-analytics/emspy#8]
When escaping a single quote in python, it turns this into a string defined with double quotes. However, emspy seems to require that the strings passed to filters be in single quotes.

All the details are here:
https://support.efoqa.com/helpdesk/tickets/33831

**Comment by delunalara** [comment]
This can be fixed by escaping the single quotes, with either

``` python
query.filter(r"'Flight Number String' == 'single quote here\''")
```

or

``` python
query.filter("'Flight Number String' == 'single quote here\\''")
```
